### ISSUE TITLE
How can I catch errors returned by the iex client?

### ISSUE THREAD

**Issue by vallamost** [JBooker10/node-iex-cloud#11]
I am calling the iex client from my own fastify server. However if I give the iex client bad input to cause an exception like an Unknown Symbol, I'm not able to catch the exception in the chain and pass it back on the response.

If I make a call to fastify like this which I expect to fail: 
GET http://localhost:4000/batch_stock_prices/?stocks=12312

I get an error response of undefined. However in the node terminal output I can see the exception as seen below.

Is the iex client swallowing errors? Is there any documentation example for how to properly catch errors with this client?

Exception:
```
09:15:00 ✨ incoming request GET xxx /batch_stock_prices/?stocks=12312
12312
Error: Unknown symbol
    at IEXRequest.<anonymous> (C:\Users\Mclovin\Desktop\modfi-stock-api\node_modules\node-iex-cloud\lib\request.js:128:35)
    at step (C:\Users\Mclovin\Desktop\modfi-stock-api\node_modules\node-iex-cloud\lib\request.js:32:23)
    at Object.next (C:\Users\Mclovin\Desktop\modfi-stock-api\node_modules\node-iex-cloud\lib\request.js:13:53)
    at fulfilled (C:\Users\Mclovin\Desktop\modfi-stock-api\node_modules\node-iex-cloud\lib\request.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
ReferenceError: response is not defined
    at getCurrentPriceOfBatchStocks (C:\Users\Mclovin\Desktop\modfi-stock-api\src\services\batch_stocks\index.js:18:12)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.<anonymous> (C:\Users\Mclovin\Desktop\modfi-stock-api\src\services\batch_stocks\index.js:53:22)
09:15:00 ✨ request completed 322ms
```

Code:
```
'use strict'

const fetch = require('node-fetch')
const { IEXCloudClient } = require("node-iex-cloud")

const iex = new IEXCloudClient(fetch, {
  sandbox: true,
  // publishable: "pk_2f78524e53454cf88afba23c327e24b5",
  publishable: "pk_2f78524e53454cf88afba23c327e24b5",
  version: "stable"
})

async function getCurrentPriceOfBatchStocks(_stock) {

  const stocks_to_submit = _stock['stocks'];
  console.log(stocks_to_submit)

  response = await iex
    .batchSymbols(stocks_to_submit)
    .price()
    .catch(function (error) {
      console.log("Exception: " + error);
      throw error;
    })

  return Promise((resolve, reject) => {
    if (response) {
      resolve(response)
    } else {
      reject(response);
    }
  });
}

const batchStocksSchema = {
  querystring: {
    type: 'object',
    properties: {
      stocks: {
        type: 'string'
      }
    },
    required: ['stocks']
  }
}

module.exports = async function (fastify, opts) {

  fastify.get('/batch_stock_prices/', {
    schema: batchStocksSchema
  }, async function (request, reply) {
    try {
      var response = await getCurrentPriceOfBatchStocks(request.query)
      // console.log(response)
      return reply
        .code(200)
        .send(response);
    } catch (e) {
      console.log(e)
      return reply
        .code(400)
        .send('Bad Request, exception: ' + e)
    }
  })

}
```

**Comment by JBooker10** [comment]
This error is on me. Since IEX gives a string of 400 on  Unknown Symbols, I didn't handle it correctly. I was expecting a json response for 400 level errors. I will be updating this package to accommodate your changes. Give me 15 min and this should be resolve. Thanks for the notice!

@awarmfastbear  feel free to let me know if you came across any other bugs

**Comment by JBooker10** [comment]
@awarmfastbear  If you do `npm i node-iex-cloud` you should be on version `2.0.2` error handling should be fixed

**Comment by JBooker10** [comment]
@awarmfastbear  Hey notice one small bug with error handling, after bring this to my attention. I've updated node-iex-cloud  again to `2.0.3` from `2.0.2`. Feel free to pushup any changes also

catching error should be easier now, i edited your code for an example. If the symbol is invalid, it should return the IEX standard error response which is a of  string "Symbol Unknown" . Sorry for  having you in circles I hope this helps

```javascript
response = await iex
    .batchSymbols(stocks_to_submit)
    .price()
    .catch(err => console.log(err)
```

**Comment by vallamost** [comment]
Thanks for your quick response!

I updated to 2.0.3 however I'm not getting any exceptions now and using the example above, the console.log statement does not print anything. Any ideas? Do I need to adjust anything else?

From my server:

```
15:49:45 ✨ Server listening at http://127.0.0.1:4000
15:49:49 ✨ incoming request GET xxx /batch_stock_prices/?stocks=asdasdfasdf
asdasdfasdf
Response: undefined
15:49:49 ✨ request completed 316ms
```

Function:

```
async function getCurrentPriceOfBatchStocks(_stock) {

  const stocks_to_submit = _stock['stocks'];
  console.log(stocks_to_submit)

  const response = await iex
    .batchSymbols(stocks_to_submit)
    .price()
    .catch(err => console.log(test: " + err) ); // < ---- doesn't print anything

  console.log("Response: " + response)

  return new Promise((resolve, reject) => {
    if (response) {
      resolve(response)
    } else {
      reject(response); 
    }
  });
}
```

**Comment by JBooker10** [comment]
The statement below is missing the `then()` block. All successful request should be returned in the success block. If it's not a successful request the `catch()` block should "catch" the errors which should be empty or "Unknown Symbol"

if you add the `then()` block and pass in the response, this should be good to go

```javascript
response = await iex
    .batchSymbols(stocks_to_submit)
    .price()
    .then(res => console.log(res))
    .catch(err => console.log(err))
```

**Comment by vallamost** [comment]
Hmmm, I don't see a difference in behavior, it instead prints out the undefined response from the `then`. You can see in the output below 'Test1' in the console log output. Seems like it is still getting swallowed somewhere in the iex client.

```
async function getCurrentPriceOfBatchStocks(_stock) {

  const stocks_to_submit = _stock['stocks'];
  console.log(stocks_to_submit)

  const response = await iex
    .batchSymbols(stocks_to_submit)
    .price()
    .then(res => console.log("Test1: " + res))
    .catch(err => console.log("Test2: " + err))

  console.log("Response: " + response)

  return new Promise((resolve, reject) => {
    if (response) {
      resolve(response)
    } else {
      reject(response); // <-- response is undefined. why?
    }
  });
}
```

Output:

```
16:43:44 ✨ incoming request GET xxx /batch_stock_prices/?stocks=asdasdfasdf
asdasdfasdf
Test1: undefined
Response: undefined
16:43:45 ✨ request completed 313ms
```

**Comment by JBooker10** [comment]
let me know if the above function  runs. I'm  kinda shooting in the dark here.  but essentially you don't need this method `getCurrentPriceOfBatchStocks(_stock)`.  I'm not too sure what this function does but this is how you would grab the response using async awaits.

```javascript
module.exports = async function (fastify, opts) {
  fastify.get(
    "/batch_stock_prices/",
    {
      schema: batchStocksSchema,
    },
    async function (request, reply) {
      try {
        const stocks_to_submit = request.query["stocks"]
       // This is the price response  that you're looking for
        const response = await iex
          .batchSymbols(stocks_to_submit)
          .price();
         // now you have access to the data to log or to send somewhere else
        console.log(response);
        // should log it correctly here
        return reply.code(200).send(response);
      } catch (e) {
        console.log(e);
        return reply.code(400).send("Bad Request, exception: " + e);
      }
    }
  );
};
```

Also if you need   `getCurrentPriceOfBatchStocks(_stock)` you can write it out as this

```javascript
async function getCurrentPriceOfBatchStocks(_stock) {
  const stocks_to_submit = _stock["stocks"];
  console.log(stocks_to_submit);
  try {
    let response = await iex.batchSymbols(stocks_to_submit).price();
    return response;
  } catch (error) {
    console.log("Exception: " + error);
    return error;
  }
}

const test = { stocks: "aapl" };

getCurrentPriceOfBatchStocks(test).then(res => console.log(res));
```

**Comment by vallamost** [comment]
Both functions return data for valid symbols but they do not catch or throw errors for invalid / unknown symbols. They just print undefined for the catch :/. Both functions also look to be returning  200s with an invalid symbol..

I used a separate function so that the web API function can remain operable and stable.

Do these functions catch invalid symbols for you and provide you an exception of invalid symbol?

I saw that you made a test on your recent commit for testing the API which would normally get a single symbol. However, have you tested the batchSymbols API with invalid symbols?

The recent test you made:
```
test("Unknown Symbol", () => {
  return iex
    .symbol("UnknownSymbol")
    .company()
    .catch(err => expect(err).toMatch("Unknown symbol"));
});
```

**Comment by JBooker10** [comment]
Yes this should work for both success and errors. You can change the line here to gibberish in the function I've made for `getCurrentPriceOfBatchStocks(_stock)` 
`const test = { stocks: "iejrigjri" };`

Also both `symbol` and `batchSymbol` both share the same request. So these changes should also be reflected in `batchSymbol`

**Comment by vallamost** [comment]
It doesn't catch the errors for me:

```
iejrigjri
20:46:46 ✨ Server listening at http://127.0.0.1:4000
undefined
```

If I change it to aapl it works fine:

```
aapl
20:47:26 ✨ Server listening at http://127.0.0.1:4000
{ AAPL: { price: 354.8 } }
```

The function I am using:

```
async function getCurrentPriceOfBatchStocks(_stock) {
  const stocks_to_submit = _stock["stocks"];
  console.log(stocks_to_submit);
  try {
    let response = await iex.batchSymbols(stocks_to_submit).price();
    return response;
  } catch (error) {
    console.log("Exception: " + error);
    return error;
  }
}

const test = { stocks: "iejrigjri" };

getCurrentPriceOfBatchStocks(test).then(res => console.log(res));
```

**Comment by JBooker10** [comment]
I think I understand what's going on now. I was using `axios` as my http client and you are using `node-fetch`. These libraries handle errors slightly differently. I will fix this bug. But can you try using axios for now to see what happens?

 If you have axios it should be coming back as `Unkown Symbol`. Sorry that's my fault, good find. Will update this to support `node-fetch`

**Comment by vallamost** [comment]
Ahh! Good catch! That was it. As soon as I switched to axios it returned the Unknown Symbol response. Is axios typically preferred over fetch in most cases?

**Comment by JBooker10** [comment]
Awesome! Axios has much better error handling, but It's really all about preference. I typically use axios on both server and client side

Also I updated the package if you would like to still use node-fetch

**Comment by vallamost** [comment]
Yeah just seeing how it supports timeouts out of the box is a no brainer to switch over to it. Thank you for your help on this!

**Comment by JBooker10** [comment]
yeah that's a good feature too and yeah no problem! If you find any other bugs. Feel free to open up another ticket
